// This file will be auto-generated by openapi-ts when backend is ready
// Run: bun run generate-client
//
// For now, export placeholder types and the API base URL

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

// Placeholder exports - will be replaced by generated client
export type ApiError = {
  detail: string
}

export type ValidationError = {
  loc: (string | number)[]
  msg: string
  type: string
}

export type HTTPValidationError = {
  detail: ValidationError[]
}

// API client placeholder - use this pattern when backend is ready
export const apiClient = {
  baseUrl: API_BASE_URL,
  // Generated methods will be added here
}
