"""Pydantic schemas for ExtraShifty."""

from .appeal import (
    AdminPendingAppealsResponse,
    AppealCreate,
    AppealListResponse,
    AppealResponse,
    AppealReviewRequest,
    AppealReviewResponse,
    AppealWithdrawResponse,
    EmergencyWaiverStatusResponse,
    SuspensionListResponse,
    SuspensionResponse,
)
from .agency import (
    AgencyClientForShift,
    AgencyClientListForShifts,
    AgencyDashboardResponse,
    AgencyEarningsSummary,
    AgencyModeRequirements,
    AgencyModeUpdateRequest,
    AgencyModeUpdateResponse,
    AgencyPaymentSummary,
    AgencyProfileCreate,
    AgencyProfileRead,
    AgencyProfileUpdate,
    AgencySettlementPreview,
    AgencyShiftCreateForClient,
    AgencyShiftListResponse,
    AgencyShiftResponse,
)
from .application import ApplicationCreate, ApplicationRead, ApplicationUpdate
from .notification import (
    NotificationCreate,
    NotificationListResponse,
    NotificationPreferenceRead,
    NotificationPreferenceUpdate,
    NotificationRead,
    NotificationUpdate,
)
from .payment import (
    AutoTopupConfigRequest,
    AutoTopupConfigResponse,
    BalanceResponse,
    CancellationPolicy,
    CancellationRequest,
    CancellationResponse,
    CancelledBy,
    InsufficientFundsResponse,
    PayoutHistoryItem,
    PayoutHistoryResponse,
    PayoutRequest,
    PayoutResponse,
    PayoutScheduleItem,
    PayoutScheduleResponse,
    PayoutStatus,
    ReserveRequest,
    ReserveResponse,
    SettlementResponse,
    SettlementSplit,
    TopupRequest,
    TopupResponse,
)
from .dispute import (
    DisputeCreate,
    DisputeListResponse,
    DisputeResolution,
    DisputeResolutionResponse,
    DisputeResolutionType,
    DisputeResponse,
    DisputeUpdate,
    EvidenceCreate,
    EvidenceResponse,
)
from .gdpr import (
    AdminDeletionRequestResponse,
    DataExportDownloadResponse,
    DataExportResponse,
    DeletionRequestCreate,
    DeletionRequestListResponse,
    DeletionRequestResponse,
    DeletionStatusResponse,
)
from .review import ReviewCreate, ReviewListResponse, ReviewRead, ReviewStats
from .shift import ShiftCreate, ShiftRead, ShiftUpdate
from .tax import (
    Generate1099Request,
    Generate1099Response,
    PendingW9Response,
    TaxDocumentListResponse,
    TaxDocumentResponse,
    TaxStatusResponse,
    TaxYearSummary,
    W9SubmitRequest,
    W9SubmitResponse,
)
from .token import Token, TokenPayload
from .user import UserCreate, UserLogin, UserRead, UserUpdate
from .verification import (
    HoursAdjustmentRequest,
    PendingShiftResponse,
    PendingShiftsListResponse,
    ShiftApprovalRequest,
    ShiftApprovalResponse,
    ShiftRejectionRequest,
    ShiftRejectionResponse,
)
from .wallet import (
    PaymentMethodCreate,
    PaymentMethodListResponse,
    PaymentMethodRead,
    TopUpRequest,
    TopUpResponse,
    TransactionListResponse,
    TransactionRead,
    WalletRead,
    WithdrawRequest,
    WithdrawResponse,
)
from .penalty import (
    AdminPenaltySummaryResponse,
    AppealResponse as PenaltyAppealResponse,
    AppealReviewRequest as PenaltyAppealReviewRequest,
    AppealReviewResponse as PenaltyAppealReviewResponse,
    LiftSuspensionRequest,
    NegativeBalanceResponse,
    PenaltyAppealRequest,
    PenaltyHistoryItem,
    PenaltyHistoryResponse,
    PenaltyListResponse,
    PenaltyResponse,
    PenaltySummaryResponse,
    StrikeListResponse,
    StrikeResponse,
    SuspensionResponse as PenaltySuspensionResponse,
)

__all__ = [
    # Appeal
    "AdminPendingAppealsResponse",
    "AppealCreate",
    "AppealListResponse",
    "AppealResponse",
    "AppealReviewRequest",
    "AppealReviewResponse",
    "AppealWithdrawResponse",
    "EmergencyWaiverStatusResponse",
    "SuspensionListResponse",
    "SuspensionResponse",
    # Agency
    "AgencyClientForShift",
    "AgencyClientListForShifts",
    "AgencyDashboardResponse",
    "AgencyEarningsSummary",
    "AgencyModeRequirements",
    "AgencyModeUpdateRequest",
    "AgencyModeUpdateResponse",
    "AgencyPaymentSummary",
    "AgencyProfileCreate",
    "AgencyProfileRead",
    "AgencyProfileUpdate",
    "AgencySettlementPreview",
    "AgencyShiftCreateForClient",
    "AgencyShiftListResponse",
    "AgencyShiftResponse",
    # Application
    "ApplicationCreate",
    "ApplicationRead",
    "ApplicationUpdate",
    # Notification
    "NotificationCreate",
    "NotificationListResponse",
    "NotificationPreferenceRead",
    "NotificationPreferenceUpdate",
    "NotificationRead",
    "NotificationUpdate",
    # Payment flow
    "AutoTopupConfigRequest",
    "AutoTopupConfigResponse",
    "BalanceResponse",
    "CancellationPolicy",
    "CancellationRequest",
    "CancellationResponse",
    "CancelledBy",
    "InsufficientFundsResponse",
    "PayoutHistoryItem",
    "PayoutHistoryResponse",
    "PayoutRequest",
    "PayoutResponse",
    "PayoutScheduleItem",
    "PayoutScheduleResponse",
    "PayoutStatus",
    "ReserveRequest",
    "ReserveResponse",
    "SettlementResponse",
    "SettlementSplit",
    "TopupRequest",
    "TopupResponse",
    # Wallet (legacy)
    "PaymentMethodCreate",
    "PaymentMethodListResponse",
    "PaymentMethodRead",
    "TopUpRequest",
    "TopUpResponse",
    "TransactionListResponse",
    "TransactionRead",
    "WalletRead",
    "WithdrawRequest",
    "WithdrawResponse",
    # Review
    "ReviewCreate",
    "ReviewListResponse",
    "ReviewRead",
    "ReviewStats",
    # Shift
    "ShiftCreate",
    "ShiftRead",
    "ShiftUpdate",
    # Token
    "Token",
    "TokenPayload",
    # User
    "UserCreate",
    "UserLogin",
    "UserRead",
    "UserUpdate",
    # Verification
    "HoursAdjustmentRequest",
    "PendingShiftResponse",
    "PendingShiftsListResponse",
    "ShiftApprovalRequest",
    "ShiftApprovalResponse",
    "ShiftRejectionRequest",
    "ShiftRejectionResponse",
    # Dispute
    "DisputeCreate",
    "DisputeListResponse",
    "DisputeResolution",
    "DisputeResolutionResponse",
    "DisputeResolutionType",
    "DisputeResponse",
    "DisputeUpdate",
    "EvidenceCreate",
    "EvidenceResponse",
    # Tax
    "Generate1099Request",
    "Generate1099Response",
    "PendingW9Response",
    "TaxDocumentListResponse",
    "TaxDocumentResponse",
    "TaxStatusResponse",
    "TaxYearSummary",
    "W9SubmitRequest",
    "W9SubmitResponse",
    # GDPR
    "AdminDeletionRequestResponse",
    "DataExportDownloadResponse",
    "DataExportResponse",
    "DeletionRequestCreate",
    "DeletionRequestListResponse",
    "DeletionRequestResponse",
    "DeletionStatusResponse",
    # Penalty (No-Show)
    "AdminPenaltySummaryResponse",
    "LiftSuspensionRequest",
    "NegativeBalanceResponse",
    "PenaltyAppealRequest",
    "PenaltyAppealResponse",
    "PenaltyAppealReviewRequest",
    "PenaltyAppealReviewResponse",
    "PenaltyHistoryItem",
    "PenaltyHistoryResponse",
    "PenaltyListResponse",
    "PenaltyResponse",
    "PenaltySummaryResponse",
    "PenaltySuspensionResponse",
    "StrikeListResponse",
    "StrikeResponse",
]
