/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStaffRouteImport } from './routes/onboarding/staff'
import { Route as OnboardingCompanyRouteImport } from './routes/onboarding/company'
import { Route as OnboardingAgencyRouteImport } from './routes/onboarding/agency'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LayoutWalletRouteImport } from './routes/_layout/wallet'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutShiftsIndexRouteImport } from './routes/_layout/shifts/index'
import { Route as LayoutProfileIndexRouteImport } from './routes/_layout/profile/index'
import { Route as LayoutMarketplaceIndexRouteImport } from './routes/_layout/marketplace/index'
import { Route as LayoutCompanyIndexRouteImport } from './routes/_layout/company/index'
import { Route as LayoutAgencyIndexRouteImport } from './routes/_layout/agency/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutShiftsTimeRouteImport } from './routes/_layout/shifts/time'
import { Route as LayoutShiftsApplicationsRouteImport } from './routes/_layout/shifts/applications'
import { Route as LayoutProfileUserIdRouteImport } from './routes/_layout/profile/$userId'
import { Route as LayoutMarketplaceShiftIdRouteImport } from './routes/_layout/marketplace/$shiftId'
import { Route as LayoutCompanyAgenciesRouteImport } from './routes/_layout/company/agencies'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin/users'
import { Route as LayoutAdminTransactionsRouteImport } from './routes/_layout/admin/transactions'
import { Route as LayoutAdminShiftsRouteImport } from './routes/_layout/admin/shifts'
import { Route as LayoutAdminReportsRouteImport } from './routes/_layout/admin/reports'
import { Route as LayoutAdminPayoutsRouteImport } from './routes/_layout/admin/payouts'
import { Route as LayoutAdminCompaniesRouteImport } from './routes/_layout/admin/companies'
import { Route as LayoutAdminAuditRouteImport } from './routes/_layout/admin/audit'
import { Route as LayoutAdminAgenciesRouteImport } from './routes/_layout/admin/agencies'
import { Route as LayoutAdminAdminsRouteImport } from './routes/_layout/admin/admins'
import { Route as LayoutCompanyShiftsIndexRouteImport } from './routes/_layout/company/shifts/index'
import { Route as LayoutAgencyStaffIndexRouteImport } from './routes/_layout/agency/staff/index'
import { Route as LayoutAgencyShiftsIndexRouteImport } from './routes/_layout/agency/shifts/index'
import { Route as LayoutAgencyScheduleIndexRouteImport } from './routes/_layout/agency/schedule/index'
import { Route as LayoutAgencyClientsIndexRouteImport } from './routes/_layout/agency/clients/index'
import { Route as LayoutAgencyBillingIndexRouteImport } from './routes/_layout/agency/billing/index'
import { Route as LayoutCompanyShiftsCreateRouteImport } from './routes/_layout/company/shifts/create'
import { Route as LayoutAgencyStaffInviteRouteImport } from './routes/_layout/agency/staff/invite'
import { Route as LayoutAgencyStaffMemberIdRouteImport } from './routes/_layout/agency/staff/$memberId'
import { Route as LayoutAgencyShiftsCreateRouteImport } from './routes/_layout/agency/shifts/create'
import { Route as LayoutAgencyClientsAddRouteImport } from './routes/_layout/agency/clients/add'
import { Route as LayoutAgencyBillingPayrollRouteImport } from './routes/_layout/agency/billing/payroll'
import { Route as LayoutAgencyBillingInvoicesRouteImport } from './routes/_layout/agency/billing/invoices'
import { Route as LayoutCompanyShiftsShiftIdIndexRouteImport } from './routes/_layout/company/shifts/$shiftId/index'
import { Route as LayoutAgencyClientsClientIdIndexRouteImport } from './routes/_layout/agency/clients/$clientId/index'
import { Route as LayoutCompanyShiftsShiftIdEditRouteImport } from './routes/_layout/company/shifts/$shiftId/edit'
import { Route as LayoutCompanyShiftsShiftIdApplicantsRouteImport } from './routes/_layout/company/shifts/$shiftId/applicants'
import { Route as LayoutAgencyShiftsShiftIdAssignRouteImport } from './routes/_layout/agency/shifts/$shiftId/assign'
import { Route as LayoutAgencyClientsClientIdShiftsRouteImport } from './routes/_layout/agency/clients/$clientId/shifts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStaffRoute = OnboardingStaffRouteImport.update({
  id: '/onboarding/staff',
  path: '/onboarding/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompanyRoute = OnboardingCompanyRouteImport.update({
  id: '/onboarding/company',
  path: '/onboarding/company',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAgencyRoute = OnboardingAgencyRouteImport.update({
  id: '/onboarding/agency',
  path: '/onboarding/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWalletRoute = LayoutWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShiftsIndexRoute = LayoutShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIndexRoute = LayoutProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMarketplaceIndexRoute = LayoutMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyIndexRoute = LayoutCompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgencyIndexRoute = LayoutAgencyIndexRouteImport.update({
  id: '/agency/',
  path: '/agency/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShiftsTimeRoute = LayoutShiftsTimeRouteImport.update({
  id: '/shifts/time',
  path: '/shifts/time',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShiftsApplicationsRoute =
  LayoutShiftsApplicationsRouteImport.update({
    id: '/shifts/applications',
    path: '/shifts/applications',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProfileUserIdRoute = LayoutProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMarketplaceShiftIdRoute =
  LayoutMarketplaceShiftIdRouteImport.update({
    id: '/marketplace/$shiftId',
    path: '/marketplace/$shiftId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompanyAgenciesRoute = LayoutCompanyAgenciesRouteImport.update({
  id: '/company/agencies',
  path: '/company/agencies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTransactionsRoute = LayoutAdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminShiftsRoute = LayoutAdminShiftsRouteImport.update({
  id: '/admin/shifts',
  path: '/admin/shifts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminReportsRoute = LayoutAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminPayoutsRoute = LayoutAdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminCompaniesRoute = LayoutAdminCompaniesRouteImport.update({
  id: '/admin/companies',
  path: '/admin/companies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAuditRoute = LayoutAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAgenciesRoute = LayoutAdminAgenciesRouteImport.update({
  id: '/admin/agencies',
  path: '/admin/agencies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAdminsRoute = LayoutAdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyShiftsIndexRoute =
  LayoutCompanyShiftsIndexRouteImport.update({
    id: '/company/shifts/',
    path: '/company/shifts/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyStaffIndexRoute = LayoutAgencyStaffIndexRouteImport.update({
  id: '/agency/staff/',
  path: '/agency/staff/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgencyShiftsIndexRoute = LayoutAgencyShiftsIndexRouteImport.update({
  id: '/agency/shifts/',
  path: '/agency/shifts/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgencyScheduleIndexRoute =
  LayoutAgencyScheduleIndexRouteImport.update({
    id: '/agency/schedule/',
    path: '/agency/schedule/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyClientsIndexRoute =
  LayoutAgencyClientsIndexRouteImport.update({
    id: '/agency/clients/',
    path: '/agency/clients/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyBillingIndexRoute =
  LayoutAgencyBillingIndexRouteImport.update({
    id: '/agency/billing/',
    path: '/agency/billing/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompanyShiftsCreateRoute =
  LayoutCompanyShiftsCreateRouteImport.update({
    id: '/company/shifts/create',
    path: '/company/shifts/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyStaffInviteRoute = LayoutAgencyStaffInviteRouteImport.update({
  id: '/agency/staff/invite',
  path: '/agency/staff/invite',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgencyStaffMemberIdRoute =
  LayoutAgencyStaffMemberIdRouteImport.update({
    id: '/agency/staff/$memberId',
    path: '/agency/staff/$memberId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyShiftsCreateRoute =
  LayoutAgencyShiftsCreateRouteImport.update({
    id: '/agency/shifts/create',
    path: '/agency/shifts/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyClientsAddRoute = LayoutAgencyClientsAddRouteImport.update({
  id: '/agency/clients/add',
  path: '/agency/clients/add',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgencyBillingPayrollRoute =
  LayoutAgencyBillingPayrollRouteImport.update({
    id: '/agency/billing/payroll',
    path: '/agency/billing/payroll',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyBillingInvoicesRoute =
  LayoutAgencyBillingInvoicesRouteImport.update({
    id: '/agency/billing/invoices',
    path: '/agency/billing/invoices',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompanyShiftsShiftIdIndexRoute =
  LayoutCompanyShiftsShiftIdIndexRouteImport.update({
    id: '/company/shifts/$shiftId/',
    path: '/company/shifts/$shiftId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyClientsClientIdIndexRoute =
  LayoutAgencyClientsClientIdIndexRouteImport.update({
    id: '/agency/clients/$clientId/',
    path: '/agency/clients/$clientId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompanyShiftsShiftIdEditRoute =
  LayoutCompanyShiftsShiftIdEditRouteImport.update({
    id: '/company/shifts/$shiftId/edit',
    path: '/company/shifts/$shiftId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompanyShiftsShiftIdApplicantsRoute =
  LayoutCompanyShiftsShiftIdApplicantsRouteImport.update({
    id: '/company/shifts/$shiftId/applicants',
    path: '/company/shifts/$shiftId/applicants',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyShiftsShiftIdAssignRoute =
  LayoutAgencyShiftsShiftIdAssignRouteImport.update({
    id: '/agency/shifts/$shiftId/assign',
    path: '/agency/shifts/$shiftId/assign',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutAgencyClientsClientIdShiftsRoute =
  LayoutAgencyClientsClientIdShiftsRouteImport.update({
    id: '/agency/clients/$clientId/shifts',
    path: '/agency/clients/$clientId/shifts',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/agency': typeof OnboardingAgencyRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/staff': typeof OnboardingStaffRoute
  '/admin/admins': typeof LayoutAdminAdminsRoute
  '/admin/agencies': typeof LayoutAdminAgenciesRoute
  '/admin/audit': typeof LayoutAdminAuditRoute
  '/admin/companies': typeof LayoutAdminCompaniesRoute
  '/admin/payouts': typeof LayoutAdminPayoutsRoute
  '/admin/reports': typeof LayoutAdminReportsRoute
  '/admin/shifts': typeof LayoutAdminShiftsRoute
  '/admin/transactions': typeof LayoutAdminTransactionsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/company/agencies': typeof LayoutCompanyAgenciesRoute
  '/marketplace/$shiftId': typeof LayoutMarketplaceShiftIdRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/shifts/applications': typeof LayoutShiftsApplicationsRoute
  '/shifts/time': typeof LayoutShiftsTimeRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/agency/': typeof LayoutAgencyIndexRoute
  '/company/': typeof LayoutCompanyIndexRoute
  '/marketplace/': typeof LayoutMarketplaceIndexRoute
  '/profile/': typeof LayoutProfileIndexRoute
  '/shifts/': typeof LayoutShiftsIndexRoute
  '/agency/billing/invoices': typeof LayoutAgencyBillingInvoicesRoute
  '/agency/billing/payroll': typeof LayoutAgencyBillingPayrollRoute
  '/agency/clients/add': typeof LayoutAgencyClientsAddRoute
  '/agency/shifts/create': typeof LayoutAgencyShiftsCreateRoute
  '/agency/staff/$memberId': typeof LayoutAgencyStaffMemberIdRoute
  '/agency/staff/invite': typeof LayoutAgencyStaffInviteRoute
  '/company/shifts/create': typeof LayoutCompanyShiftsCreateRoute
  '/agency/billing/': typeof LayoutAgencyBillingIndexRoute
  '/agency/clients/': typeof LayoutAgencyClientsIndexRoute
  '/agency/schedule/': typeof LayoutAgencyScheduleIndexRoute
  '/agency/shifts/': typeof LayoutAgencyShiftsIndexRoute
  '/agency/staff/': typeof LayoutAgencyStaffIndexRoute
  '/company/shifts/': typeof LayoutCompanyShiftsIndexRoute
  '/agency/clients/$clientId/shifts': typeof LayoutAgencyClientsClientIdShiftsRoute
  '/agency/shifts/$shiftId/assign': typeof LayoutAgencyShiftsShiftIdAssignRoute
  '/company/shifts/$shiftId/applicants': typeof LayoutCompanyShiftsShiftIdApplicantsRoute
  '/company/shifts/$shiftId/edit': typeof LayoutCompanyShiftsShiftIdEditRoute
  '/agency/clients/$clientId/': typeof LayoutAgencyClientsClientIdIndexRoute
  '/company/shifts/$shiftId/': typeof LayoutCompanyShiftsShiftIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/wallet': typeof LayoutWalletRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/agency': typeof OnboardingAgencyRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/staff': typeof OnboardingStaffRoute
  '/admin/admins': typeof LayoutAdminAdminsRoute
  '/admin/agencies': typeof LayoutAdminAgenciesRoute
  '/admin/audit': typeof LayoutAdminAuditRoute
  '/admin/companies': typeof LayoutAdminCompaniesRoute
  '/admin/payouts': typeof LayoutAdminPayoutsRoute
  '/admin/reports': typeof LayoutAdminReportsRoute
  '/admin/shifts': typeof LayoutAdminShiftsRoute
  '/admin/transactions': typeof LayoutAdminTransactionsRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/company/agencies': typeof LayoutCompanyAgenciesRoute
  '/marketplace/$shiftId': typeof LayoutMarketplaceShiftIdRoute
  '/profile/$userId': typeof LayoutProfileUserIdRoute
  '/shifts/applications': typeof LayoutShiftsApplicationsRoute
  '/shifts/time': typeof LayoutShiftsTimeRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/agency': typeof LayoutAgencyIndexRoute
  '/company': typeof LayoutCompanyIndexRoute
  '/marketplace': typeof LayoutMarketplaceIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/shifts': typeof LayoutShiftsIndexRoute
  '/agency/billing/invoices': typeof LayoutAgencyBillingInvoicesRoute
  '/agency/billing/payroll': typeof LayoutAgencyBillingPayrollRoute
  '/agency/clients/add': typeof LayoutAgencyClientsAddRoute
  '/agency/shifts/create': typeof LayoutAgencyShiftsCreateRoute
  '/agency/staff/$memberId': typeof LayoutAgencyStaffMemberIdRoute
  '/agency/staff/invite': typeof LayoutAgencyStaffInviteRoute
  '/company/shifts/create': typeof LayoutCompanyShiftsCreateRoute
  '/agency/billing': typeof LayoutAgencyBillingIndexRoute
  '/agency/clients': typeof LayoutAgencyClientsIndexRoute
  '/agency/schedule': typeof LayoutAgencyScheduleIndexRoute
  '/agency/shifts': typeof LayoutAgencyShiftsIndexRoute
  '/agency/staff': typeof LayoutAgencyStaffIndexRoute
  '/company/shifts': typeof LayoutCompanyShiftsIndexRoute
  '/agency/clients/$clientId/shifts': typeof LayoutAgencyClientsClientIdShiftsRoute
  '/agency/shifts/$shiftId/assign': typeof LayoutAgencyShiftsShiftIdAssignRoute
  '/company/shifts/$shiftId/applicants': typeof LayoutCompanyShiftsShiftIdApplicantsRoute
  '/company/shifts/$shiftId/edit': typeof LayoutCompanyShiftsShiftIdEditRoute
  '/agency/clients/$clientId': typeof LayoutAgencyClientsClientIdIndexRoute
  '/company/shifts/$shiftId': typeof LayoutCompanyShiftsShiftIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wallet': typeof LayoutWalletRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/agency': typeof OnboardingAgencyRoute
  '/onboarding/company': typeof OnboardingCompanyRoute
  '/onboarding/staff': typeof OnboardingStaffRoute
  '/_layout/admin/admins': typeof LayoutAdminAdminsRoute
  '/_layout/admin/agencies': typeof LayoutAdminAgenciesRoute
  '/_layout/admin/audit': typeof LayoutAdminAuditRoute
  '/_layout/admin/companies': typeof LayoutAdminCompaniesRoute
  '/_layout/admin/payouts': typeof LayoutAdminPayoutsRoute
  '/_layout/admin/reports': typeof LayoutAdminReportsRoute
  '/_layout/admin/shifts': typeof LayoutAdminShiftsRoute
  '/_layout/admin/transactions': typeof LayoutAdminTransactionsRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/company/agencies': typeof LayoutCompanyAgenciesRoute
  '/_layout/marketplace/$shiftId': typeof LayoutMarketplaceShiftIdRoute
  '/_layout/profile/$userId': typeof LayoutProfileUserIdRoute
  '/_layout/shifts/applications': typeof LayoutShiftsApplicationsRoute
  '/_layout/shifts/time': typeof LayoutShiftsTimeRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/agency/': typeof LayoutAgencyIndexRoute
  '/_layout/company/': typeof LayoutCompanyIndexRoute
  '/_layout/marketplace/': typeof LayoutMarketplaceIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/shifts/': typeof LayoutShiftsIndexRoute
  '/_layout/agency/billing/invoices': typeof LayoutAgencyBillingInvoicesRoute
  '/_layout/agency/billing/payroll': typeof LayoutAgencyBillingPayrollRoute
  '/_layout/agency/clients/add': typeof LayoutAgencyClientsAddRoute
  '/_layout/agency/shifts/create': typeof LayoutAgencyShiftsCreateRoute
  '/_layout/agency/staff/$memberId': typeof LayoutAgencyStaffMemberIdRoute
  '/_layout/agency/staff/invite': typeof LayoutAgencyStaffInviteRoute
  '/_layout/company/shifts/create': typeof LayoutCompanyShiftsCreateRoute
  '/_layout/agency/billing/': typeof LayoutAgencyBillingIndexRoute
  '/_layout/agency/clients/': typeof LayoutAgencyClientsIndexRoute
  '/_layout/agency/schedule/': typeof LayoutAgencyScheduleIndexRoute
  '/_layout/agency/shifts/': typeof LayoutAgencyShiftsIndexRoute
  '/_layout/agency/staff/': typeof LayoutAgencyStaffIndexRoute
  '/_layout/company/shifts/': typeof LayoutCompanyShiftsIndexRoute
  '/_layout/agency/clients/$clientId/shifts': typeof LayoutAgencyClientsClientIdShiftsRoute
  '/_layout/agency/shifts/$shiftId/assign': typeof LayoutAgencyShiftsShiftIdAssignRoute
  '/_layout/company/shifts/$shiftId/applicants': typeof LayoutCompanyShiftsShiftIdApplicantsRoute
  '/_layout/company/shifts/$shiftId/edit': typeof LayoutCompanyShiftsShiftIdEditRoute
  '/_layout/agency/clients/$clientId/': typeof LayoutAgencyClientsClientIdIndexRoute
  '/_layout/company/shifts/$shiftId/': typeof LayoutCompanyShiftsShiftIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/agency'
    | '/onboarding/company'
    | '/onboarding/staff'
    | '/admin/admins'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/shifts'
    | '/admin/transactions'
    | '/admin/users'
    | '/company/agencies'
    | '/marketplace/$shiftId'
    | '/profile/$userId'
    | '/shifts/applications'
    | '/shifts/time'
    | '/admin/'
    | '/agency/'
    | '/company/'
    | '/marketplace/'
    | '/profile/'
    | '/shifts/'
    | '/agency/billing/invoices'
    | '/agency/billing/payroll'
    | '/agency/clients/add'
    | '/agency/shifts/create'
    | '/agency/staff/$memberId'
    | '/agency/staff/invite'
    | '/company/shifts/create'
    | '/agency/billing/'
    | '/agency/clients/'
    | '/agency/schedule/'
    | '/agency/shifts/'
    | '/agency/staff/'
    | '/company/shifts/'
    | '/agency/clients/$clientId/shifts'
    | '/agency/shifts/$shiftId/assign'
    | '/company/shifts/$shiftId/applicants'
    | '/company/shifts/$shiftId/edit'
    | '/agency/clients/$clientId/'
    | '/company/shifts/$shiftId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/wallet'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/agency'
    | '/onboarding/company'
    | '/onboarding/staff'
    | '/admin/admins'
    | '/admin/agencies'
    | '/admin/audit'
    | '/admin/companies'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/shifts'
    | '/admin/transactions'
    | '/admin/users'
    | '/company/agencies'
    | '/marketplace/$shiftId'
    | '/profile/$userId'
    | '/shifts/applications'
    | '/shifts/time'
    | '/admin'
    | '/agency'
    | '/company'
    | '/marketplace'
    | '/profile'
    | '/shifts'
    | '/agency/billing/invoices'
    | '/agency/billing/payroll'
    | '/agency/clients/add'
    | '/agency/shifts/create'
    | '/agency/staff/$memberId'
    | '/agency/staff/invite'
    | '/company/shifts/create'
    | '/agency/billing'
    | '/agency/clients'
    | '/agency/schedule'
    | '/agency/shifts'
    | '/agency/staff'
    | '/company/shifts'
    | '/agency/clients/$clientId/shifts'
    | '/agency/shifts/$shiftId/assign'
    | '/company/shifts/$shiftId/applicants'
    | '/company/shifts/$shiftId/edit'
    | '/agency/clients/$clientId'
    | '/company/shifts/$shiftId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about'
    | '/contact'
    | '/login'
    | '/pricing'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/dashboard'
    | '/_layout/settings'
    | '/_layout/wallet'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/agency'
    | '/onboarding/company'
    | '/onboarding/staff'
    | '/_layout/admin/admins'
    | '/_layout/admin/agencies'
    | '/_layout/admin/audit'
    | '/_layout/admin/companies'
    | '/_layout/admin/payouts'
    | '/_layout/admin/reports'
    | '/_layout/admin/shifts'
    | '/_layout/admin/transactions'
    | '/_layout/admin/users'
    | '/_layout/company/agencies'
    | '/_layout/marketplace/$shiftId'
    | '/_layout/profile/$userId'
    | '/_layout/shifts/applications'
    | '/_layout/shifts/time'
    | '/_layout/admin/'
    | '/_layout/agency/'
    | '/_layout/company/'
    | '/_layout/marketplace/'
    | '/_layout/profile/'
    | '/_layout/shifts/'
    | '/_layout/agency/billing/invoices'
    | '/_layout/agency/billing/payroll'
    | '/_layout/agency/clients/add'
    | '/_layout/agency/shifts/create'
    | '/_layout/agency/staff/$memberId'
    | '/_layout/agency/staff/invite'
    | '/_layout/company/shifts/create'
    | '/_layout/agency/billing/'
    | '/_layout/agency/clients/'
    | '/_layout/agency/schedule/'
    | '/_layout/agency/shifts/'
    | '/_layout/agency/staff/'
    | '/_layout/company/shifts/'
    | '/_layout/agency/clients/$clientId/shifts'
    | '/_layout/agency/shifts/$shiftId/assign'
    | '/_layout/company/shifts/$shiftId/applicants'
    | '/_layout/company/shifts/$shiftId/edit'
    | '/_layout/agency/clients/$clientId/'
    | '/_layout/company/shifts/$shiftId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OnboardingAgencyRoute: typeof OnboardingAgencyRoute
  OnboardingCompanyRoute: typeof OnboardingCompanyRoute
  OnboardingStaffRoute: typeof OnboardingStaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/staff': {
      id: '/onboarding/staff'
      path: '/onboarding/staff'
      fullPath: '/onboarding/staff'
      preLoaderRoute: typeof OnboardingStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/company': {
      id: '/onboarding/company'
      path: '/onboarding/company'
      fullPath: '/onboarding/company'
      preLoaderRoute: typeof OnboardingCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/agency': {
      id: '/onboarding/agency'
      path: '/onboarding/agency'
      fullPath: '/onboarding/agency'
      preLoaderRoute: typeof OnboardingAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/wallet': {
      id: '/_layout/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof LayoutWalletRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shifts/': {
      id: '/_layout/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof LayoutShiftsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/marketplace/': {
      id: '/_layout/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof LayoutMarketplaceIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/': {
      id: '/_layout/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof LayoutCompanyIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/': {
      id: '/_layout/agency/'
      path: '/agency'
      fullPath: '/agency/'
      preLoaderRoute: typeof LayoutAgencyIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shifts/time': {
      id: '/_layout/shifts/time'
      path: '/shifts/time'
      fullPath: '/shifts/time'
      preLoaderRoute: typeof LayoutShiftsTimeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/shifts/applications': {
      id: '/_layout/shifts/applications'
      path: '/shifts/applications'
      fullPath: '/shifts/applications'
      preLoaderRoute: typeof LayoutShiftsApplicationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId': {
      id: '/_layout/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProfileUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/marketplace/$shiftId': {
      id: '/_layout/marketplace/$shiftId'
      path: '/marketplace/$shiftId'
      fullPath: '/marketplace/$shiftId'
      preLoaderRoute: typeof LayoutMarketplaceShiftIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/agencies': {
      id: '/_layout/company/agencies'
      path: '/company/agencies'
      fullPath: '/company/agencies'
      preLoaderRoute: typeof LayoutCompanyAgenciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/transactions': {
      id: '/_layout/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof LayoutAdminTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/shifts': {
      id: '/_layout/admin/shifts'
      path: '/admin/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof LayoutAdminShiftsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/reports': {
      id: '/_layout/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof LayoutAdminReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/payouts': {
      id: '/_layout/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof LayoutAdminPayoutsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/companies': {
      id: '/_layout/admin/companies'
      path: '/admin/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof LayoutAdminCompaniesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/audit': {
      id: '/_layout/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof LayoutAdminAuditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/agencies': {
      id: '/_layout/admin/agencies'
      path: '/admin/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof LayoutAdminAgenciesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/admins': {
      id: '/_layout/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof LayoutAdminAdminsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/shifts/': {
      id: '/_layout/company/shifts/'
      path: '/company/shifts'
      fullPath: '/company/shifts/'
      preLoaderRoute: typeof LayoutCompanyShiftsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/staff/': {
      id: '/_layout/agency/staff/'
      path: '/agency/staff'
      fullPath: '/agency/staff/'
      preLoaderRoute: typeof LayoutAgencyStaffIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/shifts/': {
      id: '/_layout/agency/shifts/'
      path: '/agency/shifts'
      fullPath: '/agency/shifts/'
      preLoaderRoute: typeof LayoutAgencyShiftsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/schedule/': {
      id: '/_layout/agency/schedule/'
      path: '/agency/schedule'
      fullPath: '/agency/schedule/'
      preLoaderRoute: typeof LayoutAgencyScheduleIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/clients/': {
      id: '/_layout/agency/clients/'
      path: '/agency/clients'
      fullPath: '/agency/clients/'
      preLoaderRoute: typeof LayoutAgencyClientsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/billing/': {
      id: '/_layout/agency/billing/'
      path: '/agency/billing'
      fullPath: '/agency/billing/'
      preLoaderRoute: typeof LayoutAgencyBillingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/shifts/create': {
      id: '/_layout/company/shifts/create'
      path: '/company/shifts/create'
      fullPath: '/company/shifts/create'
      preLoaderRoute: typeof LayoutCompanyShiftsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/staff/invite': {
      id: '/_layout/agency/staff/invite'
      path: '/agency/staff/invite'
      fullPath: '/agency/staff/invite'
      preLoaderRoute: typeof LayoutAgencyStaffInviteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/staff/$memberId': {
      id: '/_layout/agency/staff/$memberId'
      path: '/agency/staff/$memberId'
      fullPath: '/agency/staff/$memberId'
      preLoaderRoute: typeof LayoutAgencyStaffMemberIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/shifts/create': {
      id: '/_layout/agency/shifts/create'
      path: '/agency/shifts/create'
      fullPath: '/agency/shifts/create'
      preLoaderRoute: typeof LayoutAgencyShiftsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/clients/add': {
      id: '/_layout/agency/clients/add'
      path: '/agency/clients/add'
      fullPath: '/agency/clients/add'
      preLoaderRoute: typeof LayoutAgencyClientsAddRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/billing/payroll': {
      id: '/_layout/agency/billing/payroll'
      path: '/agency/billing/payroll'
      fullPath: '/agency/billing/payroll'
      preLoaderRoute: typeof LayoutAgencyBillingPayrollRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/billing/invoices': {
      id: '/_layout/agency/billing/invoices'
      path: '/agency/billing/invoices'
      fullPath: '/agency/billing/invoices'
      preLoaderRoute: typeof LayoutAgencyBillingInvoicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/shifts/$shiftId/': {
      id: '/_layout/company/shifts/$shiftId/'
      path: '/company/shifts/$shiftId'
      fullPath: '/company/shifts/$shiftId/'
      preLoaderRoute: typeof LayoutCompanyShiftsShiftIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/clients/$clientId/': {
      id: '/_layout/agency/clients/$clientId/'
      path: '/agency/clients/$clientId'
      fullPath: '/agency/clients/$clientId/'
      preLoaderRoute: typeof LayoutAgencyClientsClientIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/shifts/$shiftId/edit': {
      id: '/_layout/company/shifts/$shiftId/edit'
      path: '/company/shifts/$shiftId/edit'
      fullPath: '/company/shifts/$shiftId/edit'
      preLoaderRoute: typeof LayoutCompanyShiftsShiftIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company/shifts/$shiftId/applicants': {
      id: '/_layout/company/shifts/$shiftId/applicants'
      path: '/company/shifts/$shiftId/applicants'
      fullPath: '/company/shifts/$shiftId/applicants'
      preLoaderRoute: typeof LayoutCompanyShiftsShiftIdApplicantsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/shifts/$shiftId/assign': {
      id: '/_layout/agency/shifts/$shiftId/assign'
      path: '/agency/shifts/$shiftId/assign'
      fullPath: '/agency/shifts/$shiftId/assign'
      preLoaderRoute: typeof LayoutAgencyShiftsShiftIdAssignRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agency/clients/$clientId/shifts': {
      id: '/_layout/agency/clients/$clientId/shifts'
      path: '/agency/clients/$clientId/shifts'
      fullPath: '/agency/clients/$clientId/shifts'
      preLoaderRoute: typeof LayoutAgencyClientsClientIdShiftsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWalletRoute: typeof LayoutWalletRoute
  LayoutAdminAdminsRoute: typeof LayoutAdminAdminsRoute
  LayoutAdminAgenciesRoute: typeof LayoutAdminAgenciesRoute
  LayoutAdminAuditRoute: typeof LayoutAdminAuditRoute
  LayoutAdminCompaniesRoute: typeof LayoutAdminCompaniesRoute
  LayoutAdminPayoutsRoute: typeof LayoutAdminPayoutsRoute
  LayoutAdminReportsRoute: typeof LayoutAdminReportsRoute
  LayoutAdminShiftsRoute: typeof LayoutAdminShiftsRoute
  LayoutAdminTransactionsRoute: typeof LayoutAdminTransactionsRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
  LayoutCompanyAgenciesRoute: typeof LayoutCompanyAgenciesRoute
  LayoutMarketplaceShiftIdRoute: typeof LayoutMarketplaceShiftIdRoute
  LayoutProfileUserIdRoute: typeof LayoutProfileUserIdRoute
  LayoutShiftsApplicationsRoute: typeof LayoutShiftsApplicationsRoute
  LayoutShiftsTimeRoute: typeof LayoutShiftsTimeRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAgencyIndexRoute: typeof LayoutAgencyIndexRoute
  LayoutCompanyIndexRoute: typeof LayoutCompanyIndexRoute
  LayoutMarketplaceIndexRoute: typeof LayoutMarketplaceIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutShiftsIndexRoute: typeof LayoutShiftsIndexRoute
  LayoutAgencyBillingInvoicesRoute: typeof LayoutAgencyBillingInvoicesRoute
  LayoutAgencyBillingPayrollRoute: typeof LayoutAgencyBillingPayrollRoute
  LayoutAgencyClientsAddRoute: typeof LayoutAgencyClientsAddRoute
  LayoutAgencyShiftsCreateRoute: typeof LayoutAgencyShiftsCreateRoute
  LayoutAgencyStaffMemberIdRoute: typeof LayoutAgencyStaffMemberIdRoute
  LayoutAgencyStaffInviteRoute: typeof LayoutAgencyStaffInviteRoute
  LayoutCompanyShiftsCreateRoute: typeof LayoutCompanyShiftsCreateRoute
  LayoutAgencyBillingIndexRoute: typeof LayoutAgencyBillingIndexRoute
  LayoutAgencyClientsIndexRoute: typeof LayoutAgencyClientsIndexRoute
  LayoutAgencyScheduleIndexRoute: typeof LayoutAgencyScheduleIndexRoute
  LayoutAgencyShiftsIndexRoute: typeof LayoutAgencyShiftsIndexRoute
  LayoutAgencyStaffIndexRoute: typeof LayoutAgencyStaffIndexRoute
  LayoutCompanyShiftsIndexRoute: typeof LayoutCompanyShiftsIndexRoute
  LayoutAgencyClientsClientIdShiftsRoute: typeof LayoutAgencyClientsClientIdShiftsRoute
  LayoutAgencyShiftsShiftIdAssignRoute: typeof LayoutAgencyShiftsShiftIdAssignRoute
  LayoutCompanyShiftsShiftIdApplicantsRoute: typeof LayoutCompanyShiftsShiftIdApplicantsRoute
  LayoutCompanyShiftsShiftIdEditRoute: typeof LayoutCompanyShiftsShiftIdEditRoute
  LayoutAgencyClientsClientIdIndexRoute: typeof LayoutAgencyClientsClientIdIndexRoute
  LayoutCompanyShiftsShiftIdIndexRoute: typeof LayoutCompanyShiftsShiftIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWalletRoute: LayoutWalletRoute,
  LayoutAdminAdminsRoute: LayoutAdminAdminsRoute,
  LayoutAdminAgenciesRoute: LayoutAdminAgenciesRoute,
  LayoutAdminAuditRoute: LayoutAdminAuditRoute,
  LayoutAdminCompaniesRoute: LayoutAdminCompaniesRoute,
  LayoutAdminPayoutsRoute: LayoutAdminPayoutsRoute,
  LayoutAdminReportsRoute: LayoutAdminReportsRoute,
  LayoutAdminShiftsRoute: LayoutAdminShiftsRoute,
  LayoutAdminTransactionsRoute: LayoutAdminTransactionsRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
  LayoutCompanyAgenciesRoute: LayoutCompanyAgenciesRoute,
  LayoutMarketplaceShiftIdRoute: LayoutMarketplaceShiftIdRoute,
  LayoutProfileUserIdRoute: LayoutProfileUserIdRoute,
  LayoutShiftsApplicationsRoute: LayoutShiftsApplicationsRoute,
  LayoutShiftsTimeRoute: LayoutShiftsTimeRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAgencyIndexRoute: LayoutAgencyIndexRoute,
  LayoutCompanyIndexRoute: LayoutCompanyIndexRoute,
  LayoutMarketplaceIndexRoute: LayoutMarketplaceIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutShiftsIndexRoute: LayoutShiftsIndexRoute,
  LayoutAgencyBillingInvoicesRoute: LayoutAgencyBillingInvoicesRoute,
  LayoutAgencyBillingPayrollRoute: LayoutAgencyBillingPayrollRoute,
  LayoutAgencyClientsAddRoute: LayoutAgencyClientsAddRoute,
  LayoutAgencyShiftsCreateRoute: LayoutAgencyShiftsCreateRoute,
  LayoutAgencyStaffMemberIdRoute: LayoutAgencyStaffMemberIdRoute,
  LayoutAgencyStaffInviteRoute: LayoutAgencyStaffInviteRoute,
  LayoutCompanyShiftsCreateRoute: LayoutCompanyShiftsCreateRoute,
  LayoutAgencyBillingIndexRoute: LayoutAgencyBillingIndexRoute,
  LayoutAgencyClientsIndexRoute: LayoutAgencyClientsIndexRoute,
  LayoutAgencyScheduleIndexRoute: LayoutAgencyScheduleIndexRoute,
  LayoutAgencyShiftsIndexRoute: LayoutAgencyShiftsIndexRoute,
  LayoutAgencyStaffIndexRoute: LayoutAgencyStaffIndexRoute,
  LayoutCompanyShiftsIndexRoute: LayoutCompanyShiftsIndexRoute,
  LayoutAgencyClientsClientIdShiftsRoute:
    LayoutAgencyClientsClientIdShiftsRoute,
  LayoutAgencyShiftsShiftIdAssignRoute: LayoutAgencyShiftsShiftIdAssignRoute,
  LayoutCompanyShiftsShiftIdApplicantsRoute:
    LayoutCompanyShiftsShiftIdApplicantsRoute,
  LayoutCompanyShiftsShiftIdEditRoute: LayoutCompanyShiftsShiftIdEditRoute,
  LayoutAgencyClientsClientIdIndexRoute: LayoutAgencyClientsClientIdIndexRoute,
  LayoutCompanyShiftsShiftIdIndexRoute: LayoutCompanyShiftsShiftIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OnboardingAgencyRoute: OnboardingAgencyRoute,
  OnboardingCompanyRoute: OnboardingCompanyRoute,
  OnboardingStaffRoute: OnboardingStaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
